package controllers

import "testing"

// guardModel is a model with several hosts, plain paths, a regex route,
// headers, annotation-derived settings and a passthrough host: no solver.
func guardModel() *renderModel {
	m := newRenderModel()
	tru, fls := true, false
	var ct, rt, bs uint64 = 7, 30, 1048576
	status := uint64(301)
	m.sticky = true
	m.hostCert["app.example.com"] = "app.example.com"
	m.addRoute("app.example.com", "/", []backend{{addr: "web:80", weight: 3}, {addr: "web2:80", weight: 1}},
		annSettings{ssl: &tru, http2: &tru, forceHTTPS: &tru, connectTimeout: &ct, readTimeout: &rt, maxBodySize: &bs,
			reqHeaders: []string{"X-A: 1"}, respHeaders: []string{"X-B: 2"}}, nil, nil)
	m.addRoute("app.example.com", "/api/", []backend{{addr: "api:8080"}},
		annSettings{healthcheck: &fls, disableAccessLog: &tru}, []string{"X-Extra: e"}, nil)
	m.addRegexRoute("app.example.com", `/v\d+/items`, []backend{{addr: "items:80"}}, annSettings{}, nil, nil)
	m.addRoute("old.example.com", "/", []backend{{addr: "old:80"}},
		annSettings{redirectStatus: &status, redirectLocation: "https://app.example.com/"}, nil, nil)
	m.addRoute("*.wild.example.com", "/static", []backend{{addr: "static:80"}}, annSettings{healthcheck: &tru}, nil, []string{"X-Resp: y"})
	m.addPassthroughHost("raw.example.com", "10.0.0.5:443")
	return m
}

// What is written for a model without a solver is what it was before solvers
// became routes of their host in every mode. The strings were captured from
// the writers at the commit before that change.
func TestRender_WithoutSolversTheFilesAreAsTheyWere(t *testing.T) {
	if got := renderUpstreams(guardModel()); got != guardV1 {
		t.Errorf("v1 file changed:\n%s", got)
	}
	if got := renderUpstreamsV2(guardModel()); got != guardV2 {
		t.Errorf("older modes' v2 file changed:\n%s", got)
	}
}

const guardV1 = `# Generated by synapse-operator ingress controller. Do not edit.
sticky_sessions: true
upstreams:
  "*.wild.example.com":
    paths:
      "/static":
        servers:
          - "static:80"
        ssl_enabled: false
        healthcheck: true
        response_headers:
          - "X-Resp: y"
  "app.example.com":
    certificate: "app.example.com"
    paths:
      "/":
        servers:
          - { address: "web:80", weight: 3 }
          - { address: "web2:80", weight: 1 }
        ssl_enabled: true
        http2_enabled: true
        https_proxy_enabled: true
        connection_timeout: 7
        read_timeout: 30
        max_body_size: 1048576
        request_headers:
          - "X-A: 1"
        response_headers:
          - "X-B: 2"
      "/api":
        servers:
          - "api:8080"
        ssl_enabled: false
        healthcheck: false
        disable_access_log: true
        request_headers:
          - "X-Extra: e"
        response_headers: []
      "expr:/v\\d+/items":
        servers:
          - "items:80"
        match_expr: "http.request.path matches \"^/v\\d+/items\""
        ssl_enabled: false
  "old.example.com":
    paths:
      "/":
        servers:
          - "old:80"
        ssl_enabled: false
        redirect:
          status: 301
          location: "https://app.example.com/"
`

const guardV2 = `# Generated by synapse-operator ingress controller. Do not edit.
version: 2
proxy:
  sticky_sessions:
    enabled: true
hosts:
  "*.wild.example.com":
    tls:
      terminate: {}
    paths:
      "/static":
        upstream: "static:80"
        health_check:
          type: tcp
        headers:
          response:
            - "X-Resp: y"
  "app.example.com":
    tls:
      terminate:
        cert: "app.example.com"
    paths:
      "/":
        upstreams:
          - { addr: "web:80", weight: 3 }
          - { addr: "web2:80", weight: 1 }
        ssl_enabled: true
        http2_enabled: true
        force_https: true
        max_body_size: 1048576
        timeouts:
          connect: 7
          read: 30
        headers:
          request:
            - "X-A: 1"
          response:
            - "X-B: 2"
      "/api":
        upstream: "api:8080"
        disable_access_log: true
        headers:
          request:
            - "X-Extra: e"
      "expr:/v\\d+/items":
        upstream: "items:80"
        match_expr: "http.request.path matches \"^/v\\d+/items\""
  "old.example.com":
    tls:
      terminate: {}
    paths:
      "/":
        upstream: "old:80"
        redirect:
          status: 301
          location: "https://app.example.com/"
  "raw.example.com":
    tls:
      passthrough: true
    upstream: "10.0.0.5:443"
`
